name: Kareem
favicon: null
layout_spectrum: 0.983469492290169
typography_spectrum: 0.8375847209244967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6611001405399293
  lightness: 0.6296981775667518
  saturation: 0.3924850048497319
  rhythmicContrast: 0.4310298420023173
purpose: []
